apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner
  labels:
    app.kubernetes.io/name: learner
    app.kubernetes.io/component: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: learner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: learner
        app.kubernetes.io/component: training
    spec:
      containers:
      - name: learner
        image: nimbusguard-learner:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: MINIO_ENDPOINT
          value: "http://minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: MINIO_BUCKET
          value: "models"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
