apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbusguard
  labels:
    app: nimbusguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimbusguard
  template:
    metadata:
      labels:
        app: nimbusguard
    spec:
      containers:
      - name: nimbusguard
        image: nimbusguard:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: WORKERS
          value: "4"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3 