apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base resources (namespaces, CRDs)
resources:
- base
- components
- monitoring

# Apply components in order: base first (namespaces), then components, then monitoring

# Common labels for all resources

# Common annotations
commonAnnotations:
  app.kubernetes.io/version: 1.0.0
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: nimbusguard-platform
