apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-root

resources:
  - overlays/development

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: nimbusguard
  app.kubernetes.io/instance: nimbusguard
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: application
  app.kubernetes.io/part-of: nimbusguard-platform
  app.kubernetes.io/managed-by: kustomize 