apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base resources (namespaces, CRDs)
resources:
  - base
  - components
  - monitoring

# Apply components in order: base first (namespaces), then components, then monitoring
patchesStrategicMerge: []

# Common labels for all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: nimbusguard-platform

# Common annotations
commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
