apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-platform
  annotations:
    config.kubernetes.io/local-config: "true"

# Base components
resources:
- base

# Additional components
- components/observability
- components/keda

commonLabels:
  app.kubernetes.io/part-of: nimbusguard
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize

namespace: nimbusguard

# Image configurations
images:
- name: nimbusguard/consumer-workload
  newTag: latest
- name: nimbusguard/load-generator
  newTag: latest
- name: nimbusguard/langgraph-operator
  newTag: latest

# Configuration patches
patchesStrategicMerge:
- patches/production-resources.yaml

configMapGenerator:
- name: deployment-info
  literals:
  - deployment.timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  - deployment.version="0.1.0"
  - deployment.environment="kubernetes" 