apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-hpa-baseline
  labels:
    component: consumer
    evaluation: baseline
    research: "true"
    test-scenario: "hpa-baseline"
  annotations:
    research.note: "Baseline HPA for testing - faster scale-down for observing behavior"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  minReplicas: 2
  maxReplicas: 50
  metrics:
  # CPU-based scaling (same thresholds)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling (same thresholds)
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  
      selectPolicy: Min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30  
      selectPolicy: Min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15 