apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/monitoring
  - ../../components/consumer
  - ../../components/dqn-adapter
  - ../../components/redis
  - ../../components/minio
  - ../../components/keda
  - ../../components/mcp-server

namespace: nimbusguard

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  # Add production-specific patches here
  # - replica-patch.yaml
  # - keda-patch.yaml
  # - resource-limits-patch.yaml

images:
  # Override images for production
  # - name: nimbusguard-consumer
  #   newTag: v1.0.0 