apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-production

namespace: nimbusguard

resources:
  - ../../base
  - ingress.yaml
  - networkpolicy.yaml
  - pdb.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml

# Production image tag
images:
  - name: nimbusguard
    newTag: latest

# Add production labels
labels:
  - pairs:
      environment: production
  
# Add annotations for production
commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  managed-by: kustomize-prod 