apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nimbusguard-pdb
  labels:
    app: nimbusguard
    app.kubernetes.io/component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nimbusguard 