apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-observability
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- prometheus.yaml
- grafana.yaml
- tempo.yaml
- loki.yaml
- opentelemetry.yaml

commonLabels:
  app.kubernetes.io/part-of: nimbusguard
  app.kubernetes.io/component: observability
  app.kubernetes.io/managed-by: kustomize

namespace: nimbusguard 