apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - loki.yaml
  - tempo.yaml
  - grafana.yaml

namespace: monitoring

commonLabels:
  app.kubernetes.io/part-of: nimbusguard-monitoring
  app.kubernetes.io/managed-by: kustomize
