apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus.yaml
- loki.yaml
- tempo.yaml
- grafana.yaml
- node-exporter.yaml

namespace: monitoring

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: nimbusguard-monitoring
