apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-monitoring

namespace: monitoring

resources:
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafana-dashboard.yaml

labels:
  - pairs:
      app.kubernetes.io/name: nimbusguard
      app.kubernetes.io/component: monitoring 