apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nimbusguard-metrics
  labels:
    app: nimbusguard
    app.kubernetes.io/component: monitoring
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nimbusguard
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - nimbusguard 