apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nimbusguard

resources:
  - ../../resources

components:
  - ../../components/consumer
  - ../../components/operator
  - ../../components/redis
  - ../../components/minio
  - ../../components/monitoring
  - ../../components/dashboards
  - ../../components/load-generator
  - ../../components/keda
  - ../../components/mcp-server

labels:
  - pairs:
      app: nimbusguard
      environment: development