apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-development

namespace: nimbusguard

resources:
  - ../../base
  - ingress.yaml
  - networkpolicy.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

# Development specific configurations
configMapGenerator:
  - name: nimbusguard-dev-config
    literals:
      - DEBUG=true
      - LOG_LEVEL=debug
      - ENVIRONMENT=development

# Development image tag
images:
  - name: nimbusguard
    newTag: fixed-logging

# Add development labels
labels:
  - pairs:
      environment: development
  
# Add annotations for development
commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  managed-by: kustomize-dev 