apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nimbusguard

bases:
  - ../../base

components:
  - ../../components/consumer
  - ../../components/dqn-adapter
  - ../../components/learner
  - ../../components/redis
  - ../../components/minio
  - ../../components/monitoring
  - ../../components/keda
  - ../../components/kserve
  - ../../components/mcp-server

labels:
  - pairs:
      app: nimbusguard
      environment: development

patchesStrategicMerge:
  # Add development-specific patches here
  # - replica-patch.yaml

images:
  # Override images for development
  # - name: nimbusguard-consumer
  #   newTag: dev 