apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/consumer
  - ../../components/monitoring

namespace: nimbusguard

labels:
  - pairs:
      app: nimbusguard
      environment: development

patchesStrategicMerge:
  # Add development-specific patches here
  # - replica-patch.yaml

images:
  # Override images for development
  # - name: nimbusguard-consumer
  #   newTag: dev 