apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - consumer-workload.yaml
  - load-generator.yaml
  - kafka.yaml
  - keda-scaler.yaml

namespace: nimbusguard

commonLabels:
  app.kubernetes.io/name: nimbusguard
  app.kubernetes.io/part-of: nimbusguard
  app.kubernetes.io/component: operator 