apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-burst-quick
  labels:
    load-test: burst-quick
spec:
  template:
    metadata:
      labels:
        load-test: burst-quick
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-consumer
        image: curlimages/curl:8.5.0
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for consumer service to be ready..."
          until curl -f -s http://consumer:8000/health > /dev/null; do
            echo "Consumer not ready, waiting 5 seconds..."
            sleep 5
          done
          echo "Consumer service is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      containers:
      - name: load-generator
        image: nimbusguard-generator:latest
        imagePullPolicy: IfNotPresent
        args:
        - --url=http://consumer:8000
        - --test-name=Burst Scale Test
        - --description=High-intensity burst to force immediate scaling
        - --concurrent=20
        - --total=80
        - --cpu-intensity=10
        - --memory-size=300
        - --duration=10
        - --delay=0.5
        - --async-mode
        - --monitor
        - --cleanup
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  backoffLimit: 1
  activeDeadlineSeconds: 90  # 1.5 minutes max 