apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-memory-stress
  labels:
    load-test: memory-stress
spec:
  template:
    metadata:
      labels:
        load-test: memory-stress
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-consumer
        image: curlimages/curl:8.5.0
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for consumer service to be ready..."
          until curl -f -s http://consumer:8000/health > /dev/null; do
            echo "Consumer not ready, waiting 5 seconds..."
            sleep 5
          done
          echo "Consumer service is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      containers:
      - name: load-generator
        image: nimbusguard-generator:latest
        imagePullPolicy: IfNotPresent
        args:
        - --url=http://consumer:8000
        - --test=memory_stress
        - --monitor
        - --cleanup
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"  # Higher memory for memory stress test
            cpu: "200m"
  backoffLimit: 1
  activeDeadlineSeconds: 600  # 10 minutes max 