apiVersion: batch/v1
kind: Job
metadata:
  name: load-test-baseline
  namespace: nimbusguard
  labels:
    load-test: baseline-continuous-hpa
    experiment: continuous-scaling-test
spec:
  template:
    metadata:
      labels:
        load-test: load-test-baseline
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-consumer
        image: curlimages/curl:8.5.0
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for consumer service to be ready..."
          until curl -f -s http://consumer:8000/health > /dev/null; do
            echo "Consumer not ready, waiting 5 seconds..."
            sleep 5
          done
          echo "Consumer service is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      containers:
      - name: load-generator
        image: nimbusguard-generator:latest
        imagePullPolicy: Always
        command: ['bash', '-c']
        args:
        - |-
          echo "Starting Baseline Continuous HPA Scaling Test"

          # Phase 1: Warm-up
          echo "Phase 1/4: Concurrent=4, Total=40"
          python load_generator.py \
            --url=http://consumer:8000 \
            --concurrent=4 \
            --total=40 \
            --delay=3.0

          # Phase 2: Gradual Ramp-up
          echo "Phase 2/4: Concurrent=8, Total=60"
          python load_generator.py \
            --url=http://consumer:8000 \
            --concurrent=8 \
            --total=60 \
            --delay=2.0

          # Phase 3: Peak Load
          echo "Phase 3/4: Concurrent=15, Total=90"
          python load_generator.py \
            --url=http://consumer:8000 \
            --concurrent=15 \
            --total=90 \
            --delay=1.5

          # Phase 4: Gradual Cooldown
          echo "Phase 4/4: Concurrent=3, Total=30"
          python load_generator.py \
            --url=http://consumer:8000 \
            --concurrent=3 \
            --total=30 \
            --delay=4.0

          echo "4-Phase test complete"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  backoffLimit: 1
  activeDeadlineSeconds: 2400