apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # Job templates - uncomment the ones you want to deploy with kustomize
  # Alternatively, use individual 'make load-test-*' commands to run specific tests
  # - job-light.yaml
  # - job-medium.yaml  
  # - job-heavy.yaml
  # - job-sustained.yaml
  # - job-burst.yaml
  # - job-memory-stress.yaml
  # - job-cpu-stress.yaml
  # - job-comparison-baseline.yaml 
  - cronjob-production.yaml

labels:
  - pairs:
      component: load-generator 