apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqn-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dqn-adapter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dqn-adapter
        component: dqn-adapter
      annotations:
        # This annotation is crucial. It tells Alloy/Prometheus to scrape this pod.
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/healthz"
    spec:
      serviceAccountName: dqn-adapter-sa
      containers:
      - name: adapter
        # NOTE: You will need to build and push this image to your registry.
        image: nimbusguard-dqn-adapter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
        - containerPort: 8080
          name: metrics
        env:
        # OpenAI API key for LLM validation
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key # Assumes a secret named 'openai-api-key' exists
              key: key
        # Service URLs
        - name: PROMETHEUS_URL
          value: "http://prometheus.nimbusguard.svc:9090"
        - name: MCP_SERVER_URL
          value: "http://mcp-server.nimbusguard.svc:8080"
        - name: REDIS_URL
          value: "redis://redis.nimbusguard.svc:6379"
        # AI Model Configuration (cost-effective)
        - name: AI_MODEL
          value: "gpt-3.5-turbo"  # More cost-effective than gpt-4o-mini
        - name: AI_TEMPERATURE
          value: "0.1"  # Low temperature for consistent reasoning
        # Explainable AI Configuration
        - name: ENABLE_DETAILED_REASONING
          value: "true"  # Enable comprehensive AI reasoning logs
        - name: REASONING_LOG_LEVEL
          value: "INFO"  # INFO for production, DEBUG for development
        # Configuration  
        - name: POLLING_INTERVAL
          value: "5"
        - name: TARGET_DEPLOYMENT
          value: "consumer"
        - name: TARGET_NAMESPACE
          value: "nimbusguard"
        - name: STABILIZATION_PERIOD_SECONDS
          value: "5"
        - name: REWARD_LATENCY_WEIGHT
          value: "10.0"
        - name: REWARD_REPLICA_COST
          value: "0.1"
        - name: PYTHONUNBUFFERED
          value: "1"
        readinessProbe:
          exec:
            command:
            - timeout
            - "5"
            - curl
            - "-f"
            - "http://localhost:8001/healthz"
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
            - timeout
            - "5"
            - curl
            - "-f"
            - "http://localhost:8001/healthz"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 