apiVersion: v1
kind: Service
metadata:
  name: dqn-adapter
spec:
  selector:
    app.kubernetes.io/name: dqn-adapter
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 