apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbusguard-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nimbusguard-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nimbusguard-operator
        component: nimbusguard-operator
      annotations:
        # This annotation is crucial. It tells Alloy/Prometheus to scrape this pod.
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: nimbusguard-operator-sa
      containers:
      - name: adapter
        # NOTE: You will need to build and push this image to your registry.
        image: nimbusguard-operator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: healthz
        env:
        # OpenAI API key for LLM validation (OPTIONAL - only needed if LLM features are enabled)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: key
              optional: true
        # Service URLs
        - name: MCP_SERVER_URL
          value: "http://mcp-server.nimbusguard.svc:8080"
        
        # === AI MODEL CONFIGURATION ===
        - name: AI_MODEL
          value: "gpt-4-turbo"  # 128K context window for complex LLM validation
        - name: AI_TEMPERATURE
          value: "0.1"  # Low temperature for consistent reasoning
        
        # === SIMPLIFIED AI CONFIGURATION ===
        - name: ENABLE_LLM_VALIDATION
          value: "false"     # DISABLED - Simplified DQN without LLM overrides
        - name: ENABLE_EXPLORATION_LENIENCY
          value: "false"     # Enable exploration leniency

        # === DQN HYPERPARAMETERS ===
        - name: DQN_GAMMA
          value: "0.95"       # Discount factor for future rewards
        - name: DQN_EPSILON
          value: "1.0"        # Initial exploration rate
        - name: DQN_EPSILON_MIN
          value: "0.01"       # Minimum exploration rate
        - name: DQN_EPSILON_DECAY
          value: "0.995"      # Epsilon decay rate per training step
        - name: DQN_LEARNING_RATE
          value: "0.001"      # Neural network learning rate
        - name: DQN_BATCH_SIZE
          value: "32"         # Training batch size
        - name: DQN_MEMORY_SIZE
          value: "2000"       # Replay buffer size
        - name: DQN_UPDATE_TARGET_FREQ
          value: "10"         # Target network update frequency
        - name: DQN_HIDDEN_UNITS
          value: "24"         # Hidden layer units
        - name: DQN_HIDDEN_LAYERS
          value: "2"          # Number of hidden layers
        
        # === DQN MODEL PERSISTENCE ===
        - name: DQN_SAVE_FREQUENCY
          value: "100"        # Save model every N training steps
        - name: DQN_SAVE_ON_IMPROVEMENT
          value: "true"       # Save when performance improves
        - name: DQN_AUTO_LOAD_MODEL
          value: "true"       # Auto-load existing model on startup
        
        # === MINIO CONFIGURATION ===
        - name: MINIO_ENDPOINT
          value: "http://minio.nimbusguard.svc:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: MINIO_BUCKET
          value: "models"
        - name: MINIO_SECURE
          value: "false"      # Use HTTP (not HTTPS)
        - name: DQN_MODEL_KEY
          value: "dqn_model.weights.h5"
        - name: DQN_METADATA_KEY
          value: "dqn_metadata.json"
        
        # === SYSTEM CONFIGURATION ===
        - name: LSTM_SEQUENCE_LENGTH
          value: "20"         # LSTM prediction sequence length
        - name: LSTM_MODEL_PATH
          value: "/tmp/memory.keras"
        - name: LSTM_SCALER_PATH
          value: "/tmp/memory.pkl"
        - name: SCALING_INTERVAL
          value: "15"         # Scaling decision interval in seconds
        - name: MIN_REPLICAS_DEFAULT
          value: "1"          # Default minimum replicas
        - name: MAX_REPLICAS_DEFAULT
          value: "10"         # Default maximum replicas
        - name: TARGET_DEPLOYMENT
          value: "consumer"   # Target deployment name
        - name: TARGET_NAMESPACE
          value: "nimbusguard"    # Target deployment namespace
        
        # === SERVER CONFIGURATION ===
        - name: SERVER_PORT
          value: "8080"       # Metrics server port
        - name: HEALTH_PORT
          value: "8081"       # Health check port
        
        # === SYSTEM CONFIGURATION ===
        - name: PYTHONUNBUFFERED
          value: "1"
        
        readinessProbe:
          exec:
            command:
            - timeout
            - "5"
            - curl
            - "-f"
            - "http://localhost:8081/healthz"
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
            - timeout
            - "5"
            - curl
            - "-f"
            - "http://localhost:8081/healthz"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 