apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbusguard-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nimbusguard-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nimbusguard-operator
        component: nimbusguard-operator
      annotations:
        # This annotation is crucial. It tells Alloy/Prometheus to scrape this pod.
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: nimbusguard-operator-sa
      containers:
      - name: adapter
        # NOTE: You will need to build and push this image to your registry.
        image: nimbusguard-operator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: healthz
        env:
        # OpenAI API key for LLM validation (OPTIONAL - only needed if LLM features are enabled)
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: key
              optional: true
        # Service URLs
        - name: PROMETHEUS_URL
          value: "http://prometheus.nimbusguard.svc:9090"
        - name: MCP_SERVER_URL
          value: "http://mcp-server.nimbusguard.svc:8080"
        
        # === AI MODEL CONFIGURATION ===
        - name: AI_MODEL
          value: "gpt-4-turbo"  # 128K context window for complex LLM validation
        - name: AI_TEMPERATURE
          value: "0.1"  # Low temperature for consistent reasoning
        
        # === SIMPLIFIED AI CONFIGURATION ===
        - name: ENABLE_LLM_VALIDATION
          value: "false"     # DISABLED - Simplified DQN without LLM overrides
        
        # === DQN CONFIGURATION ===
        - name: DQN_EPSILON_START
          value: "0.9"    # Start with 90% exploration
        - name: DQN_EPSILON_END
          value: "0.01"   # End with 1% exploration
        - name: DQN_GAMMA
          value: "0.99"       # Standard discount factor
        - name: DQN_LEARNING_RATE
          value: "0.001"       # Increased for faster training
        - name: DQN_MEMORY_CAPACITY
          value: "10000"      # Smaller replay buffer for faster learning
        - name: DQN_BATCH_SIZE
          value: "32"         # Standard batch size
        
        # === NEURAL NETWORK ARCHITECTURE ===
        - name: DQN_HIDDEN_DIMS
          value: "64,32"      # Simple 2-layer architecture
        
        # === ADVANCED DQN CONFIGURATION ===
        - name: DQN_EPSILON_DECAY
          value: "0.995"      # Epsilon decay rate per training step
        - name: DQN_MIN_REPLAY_SIZE
          value: "20"        # Reduced to enable training with current buffer size
        - name: DQN_TARGET_UPDATE_FREQUENCY
          value: "100"        # Target network update frequency
        
        # === AI FORECASTING CONFIGURATION ===
        # CRITICAL: These parameters MUST match the training configuration exactly!
        # Training used: UltraAccurateCPUForecaster (GRU) + DualTargetLSTMForecaster (LSTM)
        - name: FORECASTING_ENABLED
          value: "true"       # Enable AI forecasting
        - name: FORECASTING_HORIZON_SECONDS
          value: "15"         # Forecast 15 seconds ahead (1 step)
        - name: FORECASTING_LOOKBACK_MINUTES
          value: "15"         # Use 15 minutes of historical data for better stability
        
        # === CPU FORECASTING (GRU) CONFIGURATION ===
        # Matches: UltraAccurateCPUForecaster(sequence_length=8, prediction_steps=1)
        # Features: [cpu, cpu_ma_3, cpu_ma_5, cpu_ma_7, cpu_std_5, cpu_trend_3, cpu_momentum, cpu_hour, cpu_activity_level]
        - name: CPU_MODEL_TYPE
          value: "gru"        # CPU uses GRU architecture (NOT LSTM!)
        - name: CPU_SEQUENCE_LENGTH
          value: "8"          # CPU GRU: 8 timesteps (2 minutes @ 15s intervals)
        - name: CPU_FEATURES_COUNT
          value: "9"          # CPU uses 9 engineered features
        - name: CPU_PREDICTION_STEPS
          value: "1"          # CPU predicts 1 step ahead (15 seconds)
        
        # === MEMORY FORECASTING (LSTM) CONFIGURATION ===
        # Matches: DualTargetLSTMForecaster memory model (sequence_length=4 or 10)
        # Features: [memory, memory_ma_3, memory_ma_7, memory_std_5] 
        - name: MEMORY_MODEL_TYPE
          value: "lstm"       # Memory uses LSTM architecture
        - name: MEMORY_SEQUENCE_LENGTH
          value: "10"         # Memory LSTM: 10 timesteps to match trained model (was "4")
        - name: MEMORY_FEATURES_COUNT
          value: "4"          # Memory uses 4 engineered features
        - name: MEMORY_PREDICTION_STEPS
          value: "10"         # Memory predicts 10 steps ahead (2.5 minutes)

        
        # === SCALING CONFIGURATION ===
        - name: TARGET_DEPLOYMENT
          value: "consumer"   # Target deployment to scale
        - name: TARGET_NAMESPACE
          value: "nimbusguard"
        - name: STABILIZATION_PERIOD_SECONDS
          value: "15"         # Operator decision frequency
        
        # === SERVER CONFIGURATION ===
        - name: SERVER_PORT
          value: "8080"       # Metrics server port
        - name: HEALTH_PORT
          value: "8081"       # Health check port
        
        # === MONITORING CONFIGURATION ===
        - name: METRICS_ENABLED
          value: "true"       # Enable metrics collection
        - name: LOG_LEVEL
          value: "INFO"       # Logging level
        
        # === SYSTEM CONFIGURATION ===
        - name: PYTHONUNBUFFERED
          value: "1"
        
        readinessProbe:
          exec:
            command:
            - timeout
            - "5"
            - curl
            - "-f"
            - "http://localhost:8081/healthz"
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
            - timeout
            - "5"
            - curl
            - "-f"
            - "http://localhost:8081/healthz"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 