# IntelligentScaling Resource
apiVersion: nimbusguard.io/v1alpha1
kind: IntelligentScaling
metadata:
  name: consumer-workload
  namespace: nimbusguard
  labels:
    app: consumer-workload
    autoscaler: dqn
spec:
  namespace: nimbusguard
  target_labels:
    app: consumer-workload
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: nimbusguard
    app.kubernetes.io/part-of: nimbusguard
  minReplicas: 2
  maxReplicas: 8  # Reduced for single-node cluster

  metrics_config:
    prometheus_url: "http://prometheus.monitoring.svc.cluster.local:9090"
    tempo_url: "http://tempo.monitoring.svc.cluster.local:3200"
    loki_url: "http://loki.monitoring.svc.cluster.local:3100"
    feature_collection:
      lookback_minutes: 5

  # DQN ML configuration
  ml_config:
    # Required KServe endpoint
    kserve_endpoint: "http://nimbusguard-dqn-model.nimbusguard-serving.svc.cluster.local/v1/models/nimbusguard-dqn:predict"
    
    # Model name in KServe
    model_name: "nimbusguard-dqn"
    
    # Production confidence threshold (higher = more conservative)
    confidence_threshold: 0.7

  evaluation_config:
    evaluation_interval: 30
    trace_decisions: true
