apiVersion: v1
kind: Service
metadata:
  name: nimbusguard-operator
spec:
  selector:
    app.kubernetes.io/name: nimbusguard-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: health
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP 