apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-server
    spec:
      serviceAccount: mcp-server-sa
      containers:
      - name: mcp-kubernetes
        image: ghcr.io/feiskyer/mcp-kubernetes-server:latest
        args: ["--transport", "sse", "--port", "8080", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "timeout 5 curl -f http://localhost:8080/sse/ || true"
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "timeout 5 curl -f http://localhost:8080/sse/ || true"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3 