apiVersion: v1
kind: Service
metadata:
  name: mcp-server
spec:
  selector:
    app.kubernetes.io/name: mcp-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
