apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- minio.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/component: storage
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: nimbusguard 