---
# KEDA Namespace (if not using nimbusguard namespace)
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/part-of: nimbusguard-platform

---
# KEDA Operator Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-operator
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: operator

---
# KEDA Operator ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-operator
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: operator
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["keda.sh"]
  resources: ["*"]
  verbs: ["*"]

---
# KEDA Operator ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-operator
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-operator
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda

---
# KEDA Operator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keda
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keda
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: keda-operator
      containers:
      - name: keda-operator
        image: ghcr.io/kedacore/keda:2.12.0
        command:
        - keda
        args:
        - --leader-elect
        - --zap-log-level=info
        - --zap-encoder=console
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "keda-operator"
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 25
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5

---
# KEDA Metrics Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-metrics-apiserver
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: metrics-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keda
      app.kubernetes.io/component: metrics-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keda
        app.kubernetes.io/component: metrics-apiserver
    spec:
      serviceAccountName: keda-operator
      containers:
      - name: keda-metrics-apiserver
        image: ghcr.io/kedacore/keda-metrics-apiserver:2.12.0
        env:
        - name: WATCH_NAMESPACE
          value: ""
        args:
        - /usr/local/bin/keda-adapter
        - --secure-port=6443
        - --logtostderr=true
        - --v=0
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 5

---
# KEDA Metrics Server Service
apiVersion: v1
kind: Service
metadata:
  name: keda-metrics-apiserver
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: metrics-apiserver
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: metrics-apiserver

---
# KEDA APIService
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/component: metrics-apiserver
spec:
  service:
    name: keda-metrics-apiserver
    namespace: keda
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100 