apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # Comment out for baseline evaluation (use traditional HPA instead)
  # - scaledobject.yaml
 
labels:
  - pairs:
      component: keda-dqn 