apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-keda
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- keda-operator.yaml
- scaled-objects.yaml

commonLabels:
  app.kubernetes.io/part-of: nimbusguard
  app.kubernetes.io/component: keda
  app.kubernetes.io/managed-by: kustomize 