apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: intelligentscaling.nimbusguard.io
spec:
  group: nimbusguard.io
  names:
    kind: IntelligentScaling
    listKind: IntelligentScalingList
    plural: intelligentscaling
    singular: intelligentscaling
    shortNames:
      - isc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - namespace
                - target_labels
                - metrics_config
              properties:
                namespace:
                  type: string
                  description: Target namespace to monitor
                target_labels:
                  type: object
                  additionalProperties:
                    type: string
                  description: Labels to select target pods/deployments
                metrics_config:
                  type: object
                  required:
                    - prometheus_url
                    - metrics
                  properties:
                    prometheus_url:
                      type: string
                      default: "http://prometheus:9090"
                      description: Prometheus server URL
                    evaluation_interval:
                      type: integer
                      default: 30
                      description: Evaluation interval in seconds
                    decision_window:
                      type: string
                      default: "5m"
                      description: Time window for decision making
                    trace_decisions:
                      type: boolean
                      default: true
                      description: Enable OpenTelemetry tracing for decisions
                    metrics:
                      type: array
                      items:
                        type: object
                        required:
                          - query
                          - threshold
                        properties:
                          query:
                            type: string
                            description: PromQL query to execute
                          threshold:
                            type: number
                            description: Threshold value for the metric
                          condition:
                            type: string
                            enum: ["gt", "lt", "eq", "ne", "gte", "lte"]
                            default: "gt"
                            description: Condition to evaluate
                    action_config:
                      type: object
                      additionalProperties: true
                      description: Configuration for actions to take
                decision_engine:
                  type: string
                  default: "langgraph"
                  description: Decision engine to use (langgraph, simple)
            status:
              type: object
              properties:
                last_evaluation:
                  type: string
                  format: date-time
                  description: Last evaluation timestamp
                current_metrics:
                  type: object
                  additionalProperties:
                    type: number
                  description: Current metric values
                last_action:
                  type: string
                  description: Last action taken
                decisions_made:
                  type: integer
                  default: 0
                  description: Total number of decisions made
                trace_id:
                  type: string
                  description: OpenTelemetry trace ID of last decision
      subresources:
        status: {} 