# Updated Custom Resource Definition for a Pure DQN-based Autoscaler
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: intelligentscaling.nimbusguard.io
spec:
  group: nimbusguard.io
  names:
    kind: IntelligentScaling
    listKind: IntelligentScalingList
    plural: intelligentscaling
    singular: intelligentscaling
    shortNames:
      - isc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - namespace
                - target_labels
                - metrics_config
                - minReplicas
                - maxReplicas
              properties:
                namespace:
                  type: string
                  description: "Namespace where the target workload is deployed"
                target_labels:
                  type: object
                  description: "Labels to identify the target workload"
                  additionalProperties:
                    type: string
                minReplicas:
                  type: integer
                  description: "Minimum number of replicas"
                  minimum: 1
                  default: 1
                maxReplicas:
                  type: integer
                  description: "Maximum number of replicas"
                  minimum: 1
                  default: 10

                metrics_config:
                  type: object
                  required:
                    - prometheus_url
                  properties:
                    prometheus_url:
                      type: string
                      description: "URL of the Prometheus server"
                      default: "http://prometheus.monitoring.svc.cluster.local:9090"
                    tempo_url:
                      type: string
                      description: "URL of the Tempo server (used for context, not direct features)"
                      default: "http://tempo.monitoring.svc.cluster.local:3200"
                    loki_url:
                      type: string
                      description: "URL of the Loki server (used for context, not direct features)"
                      default: "http://loki.monitoring.svc.cluster.local:3100"

                    feature_collection:
                      type: object
                      properties:
                        lookback_minutes:
                          type: integer
                          description: "Time window for feature extraction (minutes)"
                          minimum: 1
                          maximum: 60
                          default: 5

                ml_config:
                  type: object
                  properties:
                    training_mode:
                      type: boolean
                      description: "Enable online learning and model updates"
                      default: false
                    model_path:
                      type: string
                      description: "Path to the pre-trained DQN model"
                      default: "/models/nimbusguard_dqn.pth"
                    epsilon_start:
                      type: number
                      description: "Initial exploration rate for the DQN agent"
                      minimum: 0.0
                      maximum: 1.0
                      default: 0.1
                    confidence_threshold:
                      type: number
                      description: "Minimum confidence required for the agent to take a scaling action. If below this, no action will be taken."
                      minimum: 0.0
                      maximum: 1.0
                      default: 0.3

                evaluation_config:
                  type: object
                  properties:
                    evaluation_interval:
                      type: integer
                      description: "Interval in seconds between scaling evaluations"
                      minimum: 15
                      maximum: 300
                      default: 30
                    trace_decisions:
                      type: boolean
                      description: "Enable detailed tracing for DQN decisions"
                      default: false

            status:
              type: object
              properties:
                last_evaluation:
                  type: string
                  format: date-time
                current_replicas:
                  type: integer
                target_replicas:
                  type: integer
                decision_reason:
                  type: string
                ml_status:
                  type: object
                  properties:
                    model_type:
                      type: string
                      description: "Always DQN in this version."
                    decision_type:
                      type: string
                      description: "Type of last decision (e.g., exploration, exploitation, no_action_low_confidence)"
                    confidence_score:
                      type: number
                    feature_vector_size:
                      type: integer
                    health_score:
                      type: number
                    agent_performance:
                      type: object
                      properties:
                        total_decisions:
                          type: integer
                        success_rate_percent:
                          type: number
                        current_epsilon:
                          type: number
                data_sources:
                  type: object
                  properties:
                    prometheus_available:
                      type: boolean
                    tempo_available:
                      type: boolean
                    loki_available:
                      type: boolean
                    last_feature_collection:
                      type: string
                      format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: { }
      additionalPrinterColumns:
        - name: Current
          type: integer
          description: Current replicas
          jsonPath: .status.current_replicas
        - name: Target
          type: integer
          description: Target replicas
          jsonPath: .status.target_replicas
        - name: Model
          type: string
          description: ML model type
          jsonPath: .status.ml_status.model_type
        - name: Confidence
          type: number
          description: Decision confidence
          jsonPath: .status.ml_status.confidence_score
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp