---
# Custom Resource Definition
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: intelligentscaling.nimbusguard.io
spec:
  group: nimbusguard.io
  names:
    kind: IntelligentScaling
    listKind: IntelligentScalingList
    plural: intelligentscaling
    singular: intelligentscaling
    shortNames:
      - isc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - namespace
                - target_labels
                - metrics_config
              properties:
                namespace:
                  type: string
                  description: "Namespace where the target workload is deployed"
                target_labels:
                  type: object
                  description: "Labels to identify the target workload"
                  additionalProperties:
                    type: string
                metrics_config:
                  type: object
                  required:
                    - prometheus_url
                    - evaluation_interval
                    - decision_window
                    - metrics
                  properties:
                    prometheus_url:
                      type: string
                      description: "URL of the Prometheus server"
                    evaluation_interval:
                      type: integer
                      description: "Interval in seconds between evaluations"
                      minimum: 1
                    decision_window:
                      type: string
                      description: "Time window for decision making (e.g., '5m', '1h')"
                    trace_decisions:
                      type: boolean
                      description: "Whether to trace decision-making process"
                    metrics:
                      type: array
                      items:
                        type: object
                        required:
                          - query
                          - threshold
                          - condition
                        properties:
                          query:
                            type: string
                            description: "Prometheus query to evaluate"
                          threshold:
                            type: number
                            description: "Threshold value for the metric"
                          condition:
                            type: string
                            description: "Condition to evaluate (gt, lt, eq)"
                            enum: [ gt, lt, eq ]
                decision_engine:
                  type: string
                  description: "Decision engine to use (langgraph, basic)"
                  enum: [ langgraph, basic ]
                  default: "basic"
            status:
              type: object
              properties:
                last_evaluation:
                  type: string
                  format: date-time
                  description: "Timestamp of last evaluation"
                current_replicas:
                  type: integer
                  description: "Current number of replicas"
                target_replicas:
                  type: integer
                  description: "Target number of replicas"
                decision_reason:
                  type: string
                  description: "Reason for the last scaling decision"
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: { } 