---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scalingpolicies.nimbusguard.io
  labels:
    app.kubernetes.io/name: nimbusguard
    app.kubernetes.io/component: operator
spec:
  group: nimbusguard.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              target:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required: ["apiVersion", "kind", "name"]
              scaling:
                type: object
                properties:
                  minReplicas:
                    type: integer
                    minimum: 1
                    default: 1
                  maxReplicas:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 10
                  cooldownPeriod:
                    type: integer
                    minimum: 30
                    default: 300
                  scaleUpFactor:
                    type: number
                    minimum: 1.1
                    maximum: 10.0
                    default: 2.0
                  scaleDownFactor:
                    type: number
                    minimum: 0.1
                    maximum: 0.9
                    default: 0.5
                required: ["maxReplicas"]
              aiConfig:
                type: object
                properties:
                  qLearning:
                    type: object
                    properties:
                      learningRate:
                        type: number
                        minimum: 0.001
                        maximum: 1.0
                        default: 0.1
                      discountFactor:
                        type: number
                        minimum: 0.0
                        maximum: 1.0
                        default: 0.95
                      epsilonStart:
                        type: number
                        minimum: 0.0
                        maximum: 1.0
                        default: 1.0
                      epsilonEnd:
                        type: number
                        minimum: 0.0
                        maximum: 1.0
                        default: 0.01
                      epsilonDecay:
                        type: number
                        minimum: 0.0
                        maximum: 1.0
                        default: 0.995
                  lstm:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      predictionWindow:
                        type: integer
                        minimum: 1
                        maximum: 60
                        default: 5
                      sequenceLength:
                        type: integer
                        minimum: 10
                        maximum: 120
                        default: 60
              metrics:
                type: object
                properties:
                  cpu:
                    type: object
                    properties:
                      targetUtilization:
                        type: integer
                        minimum: 1
                        maximum: 100
                        default: 70
                      threshold:
                        type: integer
                        minimum: 1
                        maximum: 100
                        default: 80
                  memory:
                    type: object
                    properties:
                      targetUtilization:
                        type: integer
                        minimum: 1
                        maximum: 100
                        default: 80
                      threshold:
                        type: integer
                        minimum: 1
                        maximum: 100
                        default: 85
                  custom:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        query:
                          type: string
                        threshold:
                          type: number
                      required: ["name", "query", "threshold"]
            required: ["target", "scaling"]
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Initializing", "Learning", "Active", "Paused", "Error"]
              currentReplicas:
                type: integer
              targetReplicas:
                type: integer
              lastScalingTime:
                type: string
                format: date-time
              lastDecision:
                type: object
                properties:
                  action:
                    type: string
                    enum: ["scale_up", "scale_down", "maintain"]
                  confidence:
                    type: number
                    minimum: 0.0
                    maximum: 1.0
                  reasoning:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
              metrics:
                type: object
                properties:
                  totalDecisions:
                    type: integer
                  successfulScalings:
                    type: integer
                  averageConfidence:
                    type: number
                  learningProgress:
                    type: number
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
    additionalPrinterColumns:
    - name: Target
      type: string
      jsonPath: .spec.target.name
    - name: Min-Replicas
      type: integer
      jsonPath: .spec.scaling.minReplicas
    - name: Max-Replicas
      type: integer
      jsonPath: .spec.scaling.maxReplicas
    - name: Current-Replicas
      type: integer
      jsonPath: .status.currentReplicas
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: scalingpolicies
    singular: scalingpolicy
    kind: ScalingPolicy
    shortNames:
    - sp
    - nsp

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aimodels.nimbusguard.io
  labels:
    app.kubernetes.io/name: nimbusguard
    app.kubernetes.io/component: operator
spec:
  group: nimbusguard.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              modelType:
                type: string
                enum: ["q-learning", "lstm", "ensemble"]
              version:
                type: string
              config:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              training:
                type: object
                properties:
                  dataSource:
                    type: string
                  schedule:
                    type: string
                  retentionPolicy:
                    type: string
                    default: "30d"
              deployment:
                type: object
                properties:
                  replicas:
                    type: integer
                    default: 1
                  resources:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
            required: ["modelType", "version"]
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Training", "Ready", "Updating", "Failed"]
              accuracy:
                type: number
              lastTrainingTime:
                type: string
                format: date-time
              lastUpdateTime:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
    additionalPrinterColumns:
    - name: Type
      type: string
      jsonPath: .spec.modelType
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Accuracy
      type: number
      jsonPath: .status.accuracy
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: aimodels
    singular: aimodel
    kind: AIModel
    shortNames:
    - aim
    - model 