apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Add your base resources here
  # - deployment.yaml
  # - service.yaml
  # - configmap.yaml

commonLabels:
  app: nimbusguard

namespace: nimbusguard 