apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nimbusguard-base

# Namespace for all resources
namespace: nimbusguard

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml

# Common labels applied to all resources
labels:
  - pairs:
      app: nimbusguard
      tier: application

# Configuration for generated resources
generatorOptions:
  disableNameSuffixHash: false

# Images to be used
images:
  - name: nimbusguard
    newTag: fixed-logging 