---
apiVersion: v1
kind: Namespace
metadata:
  name: nimbusguard
  labels:
    app.kubernetes.io/name: nimbusguard
    app.kubernetes.io/part-of: nimbusguard-platform
    kubernetes.io/metadata.name: nimbusguard
  annotations:
    opentelemetry.io/inject: "true"
    prometheus.io/scrape: "true" 