apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  selector:
    app.kubernetes.io/name: alloy
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 