apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - prometheus-rbac.yaml
  - prometheus-service.yaml
  - alloy.yaml
  - alloy-rbac.yaml
  - alloy-service.yaml
  - grafana.yaml
  - loki.yaml
  - tempo.yaml
  - beyla.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml

commonLabels:
  component: monitoring 