# Auto-instrumentation for Python FastAPI apps
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nimbusguard-auto-instrumentation
spec:
  exporter:
    endpoint: http://alloy:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.48b0
  env:
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://alloy:4318/v1/traces"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=nimbusguard"
---
# OpenTelemetry Operator (simplified single-pod deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetry-operator
    spec:
      serviceAccountName: opentelemetry-operator
      containers:
      - name: manager
        image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.113.0
        args:
        - --metrics-addr=0.0.0.0:8080
        - --enable-leader-election
        - --zap-log-level=info
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-operator
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["opentelemetry.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-operator
subjects:
- kind: ServiceAccount
  name: opentelemetry-operator
  namespace: nimbusguard 