apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- katib-experiment.yaml
- kserve-certificates.yaml
- kserve-inference.yaml
- model-storage.yaml
- continuous-training.yaml
- notebooks.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/component: kubeflow
    app.kubernetes.io/name: nimbusguard
    app.kubernetes.io/part-of: nimbusguard
